// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHnujnfIEc4r6QJIJf36SSZrTrVvpX-0',
    appId: '1:962813894182:web:749e1d6d44e747f1d350e7',
    messagingSenderId: '962813894182',
    projectId: 'contacts-6acff',
    authDomain: 'contacts-6acff.firebaseapp.com',
    storageBucket: 'contacts-6acff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6LQ-93VKiLft1hKe317dGRmIDwbxljg',
    appId: '1:962813894182:android:311bcf841ac41df5d350e7',
    messagingSenderId: '962813894182',
    projectId: 'contacts-6acff',
    storageBucket: 'contacts-6acff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1mrhVk5sNSHIk7xZYZqQ1fPxfyjOFg0',
    appId: '1:962813894182:ios:150cde85819476ebd350e7',
    messagingSenderId: '962813894182',
    projectId: 'contacts-6acff',
    storageBucket: 'contacts-6acff.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv1mrhVk5sNSHIk7xZYZqQ1fPxfyjOFg0',
    appId: '1:962813894182:ios:150cde85819476ebd350e7',
    messagingSenderId: '962813894182',
    projectId: 'contacts-6acff',
    storageBucket: 'contacts-6acff.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHnujnfIEc4r6QJIJf36SSZrTrVvpX-0',
    appId: '1:962813894182:web:04ece700ebdd6a55d350e7',
    messagingSenderId: '962813894182',
    projectId: 'contacts-6acff',
    authDomain: 'contacts-6acff.firebaseapp.com',
    storageBucket: 'contacts-6acff.appspot.com',
  );
}
